name = "RecursiveTiles"
uuid = "7d867975-de6c-4c05-9efa-f68ebc224697"
authors = ["Andrew J. Radcliffe <andrewjradcliffe@gmail.com>"]
version = "0.1.1"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
